name: "Deploy"

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  deploy:
    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master' || startsWith(github.event.comment.body, '/deploy') }}
    runs-on: ubuntu-latest
    steps:
        # checkout start
      - name: "Use pull-request-comment-branch action"
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        if: ${{ startsWith(github.event.comment.body, '/deploy') }}

      - name: "Checkout on comment"
        uses: actions/checkout@v2
        if: ${{ startsWith(github.event.comment.body, '/deploy') }}
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: "Checkout on approve"
        uses: actions/checkout@v2
        if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master' }}
        # checkout end
      - run: echo “BRANCH_NAME=$(echo $(git branch --show-current))” >> $GITHUB_ENV
      - name: test
        run: echo "this is branch, $BRANCH_NAME"
